spring.application.name=mcpserver-stdio

#H2 database properties to save the chat memory data
spring.datasource.url=jdbc:h2:file:C:/Users/C5417797/Desktop/JavaCoding/Springboot/MCP-Server-H2-DB/chat-memory
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Hemanth
spring.datasource.password=12345
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.main.web-application-type=none

logging.level.root=OFF
spring.main.banner-mode=off
logging.file.name=C:/Users/C5417797/Desktop/JavaCoding/Springboot/MCP-Server-H2-DB/mcpserver-stdio.log