spring.application.name=mcpserver-remote
server.port=8090
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n


#H2 database properties to save the chat memory data
spring.datasource.url=jdbc:h2:file:~/mcp-chat-memory
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Hemanth
spring.datasource.password=12345
# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update


spring.ai.mcp.server.protocol=STREAMABLE

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#changing the mcp server name
spring.ai.mcp.server.name=helpdesk-mcp-server
