spring.application.name=mcpclient

spring.ai.anthropic.api-key=${HAI_API_KEY}
spring.ai.anthropic.base-url=http://localhost:6655/anthropic
spring.ai.anthropic.chat.options.model=claude-sonnet-latest


logging.level.org.springframework.ai.chat.client.advisor=DEBUG


#MCP client configs
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-servers-mcpremote.json
spring.ai.mcp.client.request-timeout=60s

spring.ai.mcp.client.streamable-http.connections.mcp-remote.url=http://localhost:8090
spring.ai.mcp.client.streamable-http.connections.mcp-remote.endpoint=/mcp